import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import store from '../redux/store'

export default function Home() {
  const reviews = store.getState()
  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta charset="UTF-8" />
        <meta name="keywords" content="Create, Read, Update, Delete" />
        <meta name="author" content="Rohan Parikh" />
        <meta name="home" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <h1> This is the home page</h1>
      <ul>
          <li>
              <Link href="/">
                  <a>Home</a>
              </Link>
          </li>
          <li>
              <Link href="/WriteReview">
                  <a>Write a review</a>
              </Link>
          </li>
          <li>
              <Link href="/EditReview">
                  <a>Edit reviews</a>
              </Link>
          </li>
      </ul> 
      {
        reviews.map((rev) => (
          <div>
            <h4>{rev.title}</h4>
            <br/>
            {rev.description}
            <img src={rev.image} alt="review image"/>   
          </div>       
        ))
      }
    </div>
  )
}
